name: Terraform Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the Source branch
  push:
    branches: [ Source ]
  pull_request:
    branches: [ Source ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate & deploy:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
    - name: Check out code  
      uses: actions/checkout@v2

    - name: Run a Terraform init  
      uses: docker://hashicorp/docker/terraform:1.0.5
      with:
        entrypoint: terraform
        args: init

    - name: Run a Terraform validate    
      uses: docker://hashicorp/terraform:1.0.5
      with:
        entrypoint: terraform
        args: validate
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Terraform Apply
      run: terraform apply -auto-approve

