name: Terraform Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the Master branch and push request events only for the Dev branch.

  pull_request:
    branches:
      - master

  push:
    branches:
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code  
      uses: actions/checkout@v2

    - name: Run a Terraform init  
      run: terraform init

    - name: Setup Build AWS Credentials
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

    - name: Run a Terraform plan 
      run: terraform plan
      if: ${{ github.ref == 'refs/heads/dev' }}

    - name: Upload Playbook to S3
      uses: jakejarvis/s3-sync-action@master
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'Ansible'
      if: ${{ github.ref == 'refs/heads/master' }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      if: ${{ github.ref == 'refs/heads/master' }}

